# Configuration AWS ECS/Fargate pour le backend
# Utilise AWS CDK ou Terraform pour déployer

version: '3.8'

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/rag-photographie-backend:latest
    container_name: rag-backend-aws
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data:ro
      - ./storage:/app/storage

