name: Format and Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  # JOB 1: FORMATAGE AUTOMATIQUE EN PREMIER - TOUJOURS
  auto-format:
    name: Auto-Format Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Black and isort
      run: |
        pip install black isort
    
    - name: Format with Black (ALWAYS - NO CHECK)
      run: |
        echo "🔧 Formatage automatique des fichiers avec Black..."
        black app/ tests/
    
    - name: Format with isort (ALWAYS - NO CHECK)
      run: |
        echo "🔧 Formatage automatique des imports avec isort..."
        isort app/ tests/
    
    - name: Commit and push formatted code
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -n "$(git status --porcelain app/ tests/)" ]; then
          echo "📝 Changements détectés, commit automatique..."
          git add app/ tests/
          git commit -m "style: Auto-format code with Black and isort [skip ci]" || exit 0
          git push || exit 0
          echo "✅ Fichiers formatés et poussés automatiquement"
        else
          echo "✅ Aucun changement nécessaire, tout est déjà formaté"
        fi

  # JOB 2: LINTING (non-bloquant, après le formatage)
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: auto-format  # Attendre que le formatage soit terminé
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install linting tools
      run: |
        pip install flake8 pylint mypy
    
    - name: Run Flake8 (non-blocking)
      continue-on-error: true
      run: |
        flake8 app/ tests/ --max-line-length=120 --extend-ignore=E203,W503,E501 || true
    
    - name: Run Pylint (non-blocking)
      continue-on-error: true
      run: |
        pylint app/ --disable=C0111,C0103,R0913,R0903,W0613 || true
    
    - name: Run MyPy (non-blocking)
      continue-on-error: true
      run: |
        mypy app/ --ignore-missing-imports --no-strict-optional || true

