"""Initial migration

Revision ID: 7203b0f8bee0
Revises: 
Create Date: 2025-11-30 21:29:32.131937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7203b0f8bee0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###

